=== Geonovum/pcp-dev/XML Schema/2008-v1.2/local-IMROPCP2008.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- =================================================================== -->
<!--                                                     local-IMROPCP2008   versie 1.2                                 -->
<!--                                             versie voor lokale installatie                                               -->
<!-- =================================================================== -->
<!-- Remote versie op:																											 -->
<!-- http://schemas.geonovum.nl/imro/pcp/2008/1.2/IMROPCP2008.xsd                                                 -->
<!-- =================================================================== -->
<!-- Geonovum, Beheerorganisatie RO-Standaarden. http://ro-standaarden.geonovum.nl -->
<!-- =================================================================== -->
<!-- Version information
       20120209 gepubliceerd
     * 20120201
       update van versie 1.1 naar 1.2.
-->
<!-- =========================================================== -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml" xmlns:gml4nl="http://www.geonovum.nl/gml4nl/1.0" xmlns:imro="http://www.geonovum.nl/imro/pcp/2008/1.2" targetNamespace="http://www.geonovum.nl/imro/pcp/2008/1.2" elementFormDefault="qualified" version="1.2">
	<annotation>
		<appinfo>
			<gml4nl:ComplianceLevel>2</gml4nl:ComplianceLevel>
			<gml4nl:GMLProfileSchema>http://schemas.geonovum.nl/imro/2008/1.0/IMRO2008gmlprofile.xsd</gml4nl:GMLProfileSchema>
		</appinfo>
	</annotation>
	<import namespace="http://www.opengis.net/gml" schemaLocation="local-IMRO2008gmlprofile.xsd"/>
	<import namespace="http://www.geonovum.nl/gml4nl/1.0" schemaLocation="local-gml4nlLevels.xsd"/>
	<!-- ====================================================================== -->
	<element name="Plangebied_PCP" type="imro:Plangebied_PCPType" substitutionGroup="gml:_Feature"/>
	<complexType name="Plangebied_PCPType">
		<complexContent>
			<extension base="gml:AbstractFeatureType">
				<sequence>
					<!-- eigen idn van het betreffende ruimtelijke instrument -->
					<element name="identificatie" type="string"/>
					<!-- Bestemmingsplan / Uitwerkingsplan / Wijzigingsplan / Voorbereidingsbesluit / Plan / Visie / Besluit -->
					<element name="typePlan" type="imro:RuimtelijkPlanOfBesluit_PCPType"/>
					<!-- Waarde volgens domein -->
					<element name="beleidsmatigVerantwoordelijkeOverheid" type="imro:Overheden_PCPType"/>
					<!-- naam van de overheid; volgens format in de vorm: gemeente ..., deelgemeente/stadsdeel ..., provincie... of ministerie.... -->
					<element name="naamOverheid" type="string"/>
					<!-- CBS-nummer van de beleidsmatig verantwoordelijke overheid; 4 cijfers; ingeval Rijk: "0000"; ingeval provincie: CBS-nummer provincie, met voorafgaand 2 voorloopnegens; ingeval deelgemeente of stadsdeel: CBS-nummer gemeente -->
					<element name="overheidsCode" type="string"/>
					<!-- naam van het plan of besluit; volgens de aanhaaltitel; de volledige naam, inclusief het voorafgaand woord bestemmingsplan i.h.g.v. bestemmingsplan -->
					<element name="naam" type="gml:CodeType"/>
					<!-- samengesteld atribuut-->
					<element name="planstatusInfo" type="imro:PlanstatusEnDatum_PCPPropertyType"/>
					<element name="verwijzingNaarTekstInfo" type="imro:TekstReferentie_PCPPropertyType" minOccurs="0" maxOccurs="unbounded"/>
					<!-- IMRO2008 en PRPCP2008; verwijzing naar gebruikte versie IMRO en gebruikte versie praktijkrichtlijn: vaste waarden -->
					<element name="verwijzingNorm" type="string" minOccurs="2" maxOccurs="2"/>
					<!-- coördinaten; beschrijving van vlak of multivlak -->
					<element name="geometrie" type="imro:VlakMultiVlakPropertyType"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<!-- ====================================================================== -->
	<complexType name="PlanstatusEnDatum_PCPPropertyType">
		<sequence>
			<element ref="imro:PlanstatusEnDatum_PCP"/>
		</sequence>
	</complexType>
	<element name="PlanstatusEnDatum_PCP" type="imro:PlanstatusEnDatum_PCPType"/>
	<complexType name="PlanstatusEnDatum_PCPType">
		<sequence>
			<!-- waarde van de planstatus; één van de waarden volgens domein Planstatus_PCP -->
			<element name="planstatus" type="imro:Planstatus_PCPType"/>
			<!-- datum van de planstatus; in de vorm: jjjj-mm-dd -->
			<element name="datum" type="date"/>
		</sequence>
	</complexType>
	<simpleType name="Planstatus_PCPType">
		<restriction base="string">
			<enumeration value="concept"/>
			<enumeration value="voorontwerp"/>
			<enumeration value="ontwerp"/>
			<enumeration value="vastgesteld"/>
			<enumeration value="onherroepelijk"/>
		</restriction>
	</simpleType>
	<!-- ====================================================================== -->
	<complexType name="TekstReferentie_PCPPropertyType">
		<sequence>
			<element ref="imro:TekstReferentie_PCP"/>
		</sequence>
	</complexType>
	<element name="TekstReferentie_PCP" type="imro:TekstReferentie_PCPType"/>
	<complexType name="TekstReferentie_PCPType">
		<sequence>
			<!-- link; in format bestandsnaamconventie toelichting, voorschriften/regels conform STRI2006 -->
			<element name="verwijzingNaarTekst" type="string"/>
			<!-- één van de waarden volgens domein Teksttype_PCP -->
			<element name="typeTekst" type="imro:Teksttype_PCPType"/>
		</sequence>
	</complexType>
	<simpleType name="Teksttype_PCPType">
		<restriction base="string">
			<enumeration value="plankaart"/>
			<enumeration value="voorschriften/regels"/>
			<enumeration value="toelichting"/>
			<enumeration value="bijlage bij voorschriften/regels"/>
			<enumeration value="bijlage bij toelichting"/>
			<enumeration value="besluitdocument"/>
			<enumeration value="beleidsdocument"/>
		</restriction>
	</simpleType>
	<!-- ====================================================================== -->
	<simpleType name="RuimtelijkPlanOfBesluit_PCPType">
		<restriction base="string">
			<enumeration value="gemeentelijk plan; bestemmingsplan artikel 10"/>
			<enumeration value="gemeentelijk plan; uitwerkingsplan artikel 11"/>
			<enumeration value="gemeentelijk plan; wijzigingsplan artikel 11"/>
			<enumeration value="gemeentelijk plan; voorbereidingsbesluit"/>
			<enumeration value="gemeentelijk plan; overig"/>
			<enumeration value="provinciaal plan; overig"/>
			<enumeration value="rijksplan; overig"/>
			<enumeration value="gemeentelijke visie; overig"/>
			<enumeration value="provinciale visie; overigt"/>
			<enumeration value="rijksvisie; overig"/>
			<enumeration value="gemeentelijk besluit; overig"/>
			<enumeration value="provinciaal besluit; overig"/>
			<enumeration value="rijksbesluit; overig"/>
		</restriction>
	</simpleType>
	<!-- ====================================================================== -->
	<simpleType name="Overheden_PCPType">
		<restriction base="string">
			<enumeration value="gemeentelijke overheid"/>
			<enumeration value="deelgemeente/stadsdeel"/>
			<enumeration value="provinciale overheid"/>
			<enumeration value="nationale overheid"/>
		</restriction>
	</simpleType>
	<!-- ====================================================================== -->
	<complexType name="VlakMultiVlakPropertyType">
		<choice>
			<element ref="gml:Surface"/>
			<element ref="gml:MultiSurface"/>
		</choice>
	</complexType>
	<!-- ====================================================================== -->
</schema>

=== Geonovum/pcp-dev/Validatiebestand/Plangebied_PCP_na_IOW.xml
<?xml version="1.0" encoding="UTF-8"?>
<imro:Plangebied_PCP xmlns:gml="http://www.opengis.net/gml"
 xmlns:gml4nl="http://www.geonovum.nl/gml4nl/1.0"
 xmlns:imro="http://www.geonovum.nl/imro/pcp/2008/1.2"
 xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.geonovum.nl/imro/pcp/2008/1.2 file:/W:/Github/Geonovum/pcp-dev/XML%20Schema/2008-v1.2/local-IMROPCP2008.xsd" gml:id="ID000">
    <imro:identificatie>identificatie0</imro:identificatie>
    <imro:typePlan>gemeentelijk plan; bestemmingsplan artikel 10</imro:typePlan>
    <imro:beleidsmatigVerantwoordelijkeOverheid>gemeentelijke overheid</imro:beleidsmatigVerantwoordelijkeOverheid>
    <imro:naamOverheid>naamOverheid0</imro:naamOverheid>
    <imro:overheidsCode>overheidsCode0</imro:overheidsCode>
    <imro:naam>naam0</imro:naam>
    <imro:planstatusInfo>
        <imro:PlanstatusEnDatum_PCP>
            <imro:planstatus>concept</imro:planstatus>
            <imro:datum>2024-01-01</imro:datum>
        </imro:PlanstatusEnDatum_PCP>
    </imro:planstatusInfo>
    <imro:verwijzingNorm>verwijzingNorm0</imro:verwijzingNorm>
    <imro:verwijzingNorm>verwijzingNorm1</imro:verwijzingNorm>
    <imro:geometrie>
        <gml:MultiSurface>
        </gml:MultiSurface>
    </imro:geometrie>
</imro:Plangebied_PCP>
